# Generated by Django 3.0.8 on 2020-07-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='节点Id')),
            ],
            options={
                'db_table': 'node_info',
            },
        ),
    ]
