# Generated by Django 3.0.8 on 2020-07-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='用户名')),
                ('key', models.CharField(max_length=256, verbose_name='用户密钥')),
            ],
            options={
                'db_table': 'client_info',
            },
        ),
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='节点Id')),
                ('name', models.CharField(max_length=256, verbose_name='节点名')),
            ],
            options={
                'db_table': 'node_info',
            },
        ),
    ]
